### ISSUE TITLE
Moved Sitecore fields loose content during first deployment

### ISSUE THREAD

**Issue by zaheer-tariq** [SitecoreUnicorn/Unicorn#312] opened 2018-10-05 11:09 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If we move a template field in Sitecore (eg. from one template to a new base template), Unicorn behaves incorrectly doing the first De-serialization:
After the first Unicorn sync, the fields are empty on the item that inherit from that template. If we sync again, the fields will receive the content again.
First quick look at the logs seems to indicate that the template fields are first deleted, then re-added in a new location. It seems that Unicorn does not re-add the actual field values in the first sync, but then discovers the empty fields during next sync and correct the issue.

**If the current behavior is a bug, please provide the steps to reproduce.**
Please see above

**What is the expected behavior?**
Unicron should show the correct field values on first sync.

**Please mention your Sitecore version and Unicorn version.**
9.0 rev. 180604 (Update-2) and Unicorn Version 4.0.4

**Comment by cassidydotdk** [comment] 2018-12-16 15:52
Can I ask that you confirm if this issue is still present in 4.0.6?

We found some wonky code and it _may_ also be the root cause here.

**Comment by zaheer-tariq** [comment] 2018-12-17 17:55
Hi, Thank you for the alert. We have updated to 4.0.6 however the issue described above still exists. Can you please check and provide a fix. Thanks

**Comment by cassidydotdk** [comment] 2019-03-23 21:47
This is a duplicate of the already fixed issue, isn't it?

**Closed** 2019-05-14 19:20 UTC
