### ISSUE TITLE
Synced content created from branches doesn't set the value when new item is created

### ISSUE THREAD

**Issue by luuksommers** [SitecoreUnicorn/Unicorn#263] opened 2017-12-14 07:11 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Sync SXA content tree, the Site Grouping\{SiteName} item data is loaded from the Branch it's linked to, not the actual value from the Unicorn files. When you sync again with unicorn, the fields are updated.
![image](https://user-images.githubusercontent.com/1185823/33979828-69223128-e0a6-11e7-99a2-f27ea4c44587.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Install SXA, create Tenant and Site using SXA context menu in the content Editor
2. Update Hostname of the site in sitecore\content\{Tentant}\{Site}\Settings\Site Groupings\{Site}
3. Serialize sitecore\content\*
4. Delete content
5. Sync content, you'll see that Hostname is empty again
6. Sync content again, you'll see that Hostname is updated

**What is the expected behavior?**
Valid hostname after first sync

**Please mention your Sitecore version and Unicorn version.**
SC 8.2u3 / U 4.0.3 / SXA 1.4

**Comment by kamsar** [comment] 2018-04-01 04:25
I'm guessing this is only reproducible with SXA and not via a normal template?

I believe SXA may be using some custom logic around that field that may be causing the behavior. If you can't reproduce it with other fields, we'll need to pose the question to the SXA team to look for possible workarounds.

**Comment by bplasmeijer** [comment] 2018-04-10 14:16
do not serialize SXA; not allowed by @AdamNaj

**Comment by cassidydotdk** [comment] 2018-06-06 11:05
Closing this issue, as it has to do with SXA shenanigans

**Closed by cassidydotdk** 2018-06-06 11:05 UTC
