### ISSUE TITLE
Error while trying to sync items with "enforce version presence" enable

### ISSUE THREAD

**Issue by bartverdonck** [SitecoreUnicorn/Unicorn#280] opened 2018-03-28 09:52 UTC
**Do you want to request a *feature* or report a *bug*?**
A bug

**What is the current behavior?**
An error is returned upon syncing items that have the "enforce version presence" flag.

**If the current behavior is a bug, please provide the steps to reproduce.**
1) Create a template with on the standard value "enforce version presence" checked.
2) Create an item of that template
3) Copy the yml file to a secure place
4) Delete the item from sitecore
5) Paste the yml file back
6) Try to sync

**What is the expected behavior?**
The item should be created.

**Please mention your Sitecore version and Unicorn version.**
Sitecore 9.0.171219 (9-update1), Unicorn 4.0.3

** Error Message **
Failed to paste item: /sitecore/content/Sites/Hub/Home/Bart (Rainbow.Storage.Sc.Deserialization.DeserializationException)
at Rainbow.Storage.Sc.Deserialization.DefaultDeserializer.Deserialize(IItemData serializedItemData)
 at Unicorn.Evaluators.NewItemOnlyEvaluator.EvaluateNewSerializedItem(IItemData newItemData)
 at Unicorn.Loader.SerializationLoader.DoLoadItem(IItemData serializedItemData, IConsistencyChecker consistencyChecker)
 at Unicorn.Loader.DeserializeFailureRetryer.RetryAll(ISourceDataStore sourceDataStore, Action`1 retrySingleItemAction, Action`1 retryTreeAction)
INNER EXCEPTION
Item retrieved from the database was null. This may indicate issues with the Sitecore cache. Recycle your app pool and try again and it should work. (System.InvalidOperationException)
at Rainbow.Storage.Sc.Deserialization.DefaultDeserializer.PasteVersion(Item item, IItemVersion serializedVersion, Boolean creatingNewItem, List`1 softErrors)
 at Rainbow.Storage.Sc.Deserialization.DefaultDeserializer.PasteVersions(IItemData serializedItemData, Item targetItem, Boolean newItemWasCreated, List`1 softErrors)
 at Rainbow.Storage.Sc.Deserialization.DefaultDeserializer.Deserialize(IItemData serializedItemData)

100272 11:34:21 Unicorn.Logging.SitecoreLogger ERROR ERROR: Some directories could not be loaded. (1 inner failures)
master:/sitecore/content/Sites/Hub/Home/Bart (e85e8de9-cbe7-421a-b952-b64c497268a8) (Unicorn.DeserializationAggregateException)
at Unicorn.Loader.DeserializeFailureRetryer.RetryAll(ISourceDataStore sourceDataStore, Action`1 retrySingleItemAction, Action`1 retryTreeAction)
 at Unicorn.Loader.SerializationLoader.LoadAll(IItemData[] rootItemsData, IDeserializeFailureRetryer retryer, IConsistencyChecker consistencyChecker, Action`1 rootLoadedCallback)
 at Unicorn.SerializationHelper.SyncTree(IConfiguration configuration, Action`1 rootLoadedCallback, Boolean runSyncStartPipeline, IItemData partialSyncRoot)
 at Unicorn.SerializationHelper.SyncConfigurations(IConfiguration[] configurations, IProgressStatus progress, ILogger additionalLogger)

INNER EXCEPTION
master:/sitecore/content/Sites/Hub/Home/Bart (e85e8de9-cbe7-421a-b952-b64c497268a8) (Rainbow.Storage.Sc.Deserialization.DeserializationException)
No stack trace available.
INNER EXCEPTION
Failed to paste item: /sitecore/content/Sites/Hub/Home/Bart (Rainbow.Storage.Sc.Deserialization.DeserializationException)
at Rainbow.Storage.Sc.Deserialization.DefaultDeserializer.Deserialize(IItemData serializedItemData)
 at Unicorn.Evaluators.NewItemOnlyEvaluator.EvaluateNewSerializedItem(IItemData newItemData)
 at Unicorn.Loader.SerializationLoader.DoLoadItem(IItemData serializedItemData, IConsistencyChecker consistencyChecker)
 at Unicorn.Loader.DeserializeFailureRetryer.RetryAll(ISourceDataStore sourceDataStore, Action`1 retrySingleItemAction, Action`1 retryTreeAction)
INNER EXCEPTION
Item retrieved from the database was null. This may indicate issues with the Sitecore cache. Recycle your app pool and try again and it should work. (System.InvalidOperationException)
at Rainbow.Storage.Sc.Deserialization.DefaultDeserializer.PasteVersion(Item item, IItemVersion serializedVersion, Boolean creatingNewItem, List`1 softErrors)
 at Rainbow.Storage.Sc.Deserialization.DefaultDeserializer.PasteVersions(IItemData serializedItemData, Item targetItem, Boolean newItemWasCreated, List`1 softErrors)
 at Rainbow.Storage.Sc.Deserialization.DefaultDeserializer.Deserialize(IItemData serializedItemData)

**Comment by bartverdonck** [comment] 2018-03-28 14:48
A way to go arround it is to add the enforceversionpresencedisabler around the sync things.
I temporary fixed it in a custom DeserializeFailureRetryer.
public class EnforceVersionPresenceDisabledSync : DeserializeFailureRetryer
	{
		public override void RetryAll(ISourceDataStore sourceDataStore, Action<IItemData> retrySingleItemAction, Action<IItemData> retryTreeAction)
		{
			using (new EnforceVersionPresenceDisabler()) { 
				base.RetryAll(sourceDataStore, retrySingleItemAction, retryTreeAction);
			}
		}
	}

**Comment by kamsar** [comment] 2018-03-28 15:11
Thanks :)




On Wed, Mar 28, 2018 at 7:48 AM -0700, "Bart Verdonck" <notifications@github.com> wrote:












A way to go arround it is to add the enforceversionpresencedisabler around the sync things.

I temporary fixed it in a custom DeserializeFailureRetryer.

public class EnforceVersionPresenceDisabledSync : DeserializeFailureRetryer

{

public override void RetryAll(ISourceDataStore sourceDataStore, Action retrySingleItemAction, Action retryTreeAction)

{

using (new EnforceVersionPresenceDisabler()) {

base.RetryAll(sourceDataStore, retrySingleItemAction, retryTreeAction);

}

}

}

**Comment by mmacehardyman** [comment] 2018-05-15 06:35
I can confirm this fix works. Would be nice to see a proper fix in an upcoming release :)

**Comment by cassidydotdk** [comment] 2018-05-15 18:17
I've committed a fix to the codebase. I'm setting it up for local testing now, but feel free to give it a swing as well.

**Comment by cassidydotdk** [comment] 2018-05-16 16:36
Wait, I got it. But I had to really force it. I enabled `EnforceVersionPresence` on "website". Then I fired up Unicorn.aspx incognito, and finally it wanted to play along with me.

**Closed** 2018-05-16 17:48 UTC
Labels: bug

**Comment by GurliGebis** [comment] 2018-08-15 12:42
Please note that this breaks compatibility with Sitecore 7.2 , since it does not have the EnforceVersionPresenceDisabler class

**Comment by cassidydotdk** [comment] 2018-08-15 13:28
As for Rainbow though, it's only this one Disabler that it needs. I can work around this using Reflection - or so the current theory goes anyway
