### ISSUE TITLE
Moving template causing data loss in Shared and Unversioned Fields

### ISSUE THREAD

**Issue by zaheer-tariq** [SitecoreUnicorn/Unicorn#334] opened 2019-02-15 08:15 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Unicorn removes data/content of Shared and Unversioned fields when a template is moved to another folder. This happens to items that are not controlled by Unicorn. The data of Versioned fields is however preserved. In production the content items are not controlled by Unicorn therefore this data loss is a very BIG issue. Urgent help/support on this issue will be really appreciated.

**If the current behavior is a bug, please provide the steps to reproduce.**
1) You will need two Sitecore instances to test this scenario e.g. InstanceA and InstanceB 
2) InstanceA=> Create a new template with one Versioned, Shared and Unversioned field. Make sure this template is controlled by Unicorn. No standard values for this template.
3) InstanceA => Push the changes to git and run Unicorn Sync on InstanceB. This will create the template in InstanceB.
4) InstanceB => Create an item based on this template and add some test data to the three fields. This item is NOT controlled by Unicorn.
5) InstanceA=> Move the template created in step #2 to another folder which is also controlled by Unicorn and push the changes to Git.
6) InstanceB => Run unicorn sync, this will first remove the template from old location and will then add the template to the new location. 
7) InstanceB => Check the field values of the item created in Step # 4, you will see the data in Shared and Unversioned field is gone. The data in Versioned field however is still there.

I investigated in details and noted that the data is removed when the template is added again. I then tested if Sitecore removes the data or Unicorn by removing the template via Unicorn and adding it via Sitecore package and found that Sitecore does not remove the data. Therefore I am certain that it is Unicorn who clears Shared and Versioned fields when adding a template.

**What is the expected behavior?**
The data should not be lost in any case what so ever.

**Please mention your Sitecore version and Unicorn version.**
Sitecore = 9.0.2
Unicorn = 4.0.7

**Comment by cassidydotdk** [comment] 2019-02-15 09:11
When you move the template, is it moved across 2 separate configurations?  or are both locations predicates in the same configuration?

**Comment by zaheer-tariq** [comment] 2019-02-15 09:59
@cassidydotdk The template is moved to another folder in the same instance with same configurations.

**Comment by cassidydotdk** [comment] 2019-02-15 10:49
Show me the configs, please. And the template locations involved.

**Comment by zaheer-tariq** [comment] 2019-02-16 20:25
**Template Location**
/sitecore/templates/Feature/UnicornTest

Template was moved from /sitecore/templates/Feature/UnicornTest to /sitecore/templates/Feature/UnicornTest/SubFolder

**Related config file**
```
<configuration xmlns:patch="http://www.sitecore.net/xmlconfig/">
    <sitecore>
        <unicorn>
            <configurations>
                <configuration name="Feature.UnicornTest" description="Feature UnicornTest" >
                    <predicate>
                        <include name="Feature.UnicornTest.Templates" database="master" path="/sitecore/templates/Feature/UnicornTest"/>
                    </predicate>
                </configuration>
            </configurations>
        </unicorn>
    </sitecore>
</configuration>
```

**Comment by cassidydotdk** [comment] 2019-02-18 10:07
I need you to set Debug level logging, run the operation again and paste the logs here.

When an Item in Sitecore moves, the following log operation should take effect. I need to know if it does, and the specifics of what it logs. And if not, I need to know the additional logging.

```
		public virtual void MovedItemToNewParent(Item newParentItem, Item oldParentItem, Item movedItem)
		{
			_logger.Debug($"* [M] from {oldParentItem.ID} to {newParentItem.ID}");
		}
```

**Comment by zaheer-tariq** [comment] 2019-02-18 12:08
@cassidydotdk  Please find below log entries. Additionally I have tested that the data is actually gone from Shared and Unversioned fields (by checking in the Database directly) and it is not a cache issue.

```
14028 13:04:12 DEBUG Min threads: 8, Active threads: 1.
8612 13:04:13 INFO  AUDIT (sitecore\admin): Drag item: master:/sitecore/templates/Feature/UnicornTest/Test, language: da, version: 1, id: {646A66B2-7F74-45F0-B331-1115AB0472F1} to master:/sitecore/templates/Feature/UnicornTest/SubFolder, language: da, version: 1, id: {37E7A53C-6E74-46CC-805A-B8FC2656F7B6}
8612 13:04:13 INFO  [Unicorn]: Dilithium Serialization File System Data Store: Moved serialized item /sitecore/templates/Feature/UnicornTest/SubFolder/Test (646a66b2-7f74-45f0-b331-1115ab0472f1) to /sitecore/templates/Feature/UnicornTest/SubFolder
14028 13:04:13 DEBUG Min threads: 8, Active threads: 2.
14028 13:04:13 DEBUG Min threads: 8, Active threads: 1.
8612 13:04:14 INFO  [Unicorn]: Dilithium Serialization File System Data Store: Ignored save of /sitecore/templates/Feature/UnicornTest/SubFolder/Test because it contained no consequential item changes.
ManagedPoolThread #8 13:04:14 INFO  Job started: Index_Update_IndexName=sitecore_master_index
14028 13:04:14 DEBUG Min threads: 8, Active threads: 1.
```

**Comment by cassidydotdk** [comment] 2019-02-18 18:23
Thanks for sharing. Did you try and disable Dilithium?  That would narrow it down for me; as I can't seem to reproduce the issue here.

**Comment by zaheer-tariq** [comment] 2019-02-19 05:28
@cassidydotdk I have tried by disabling Dilithium. The result is the same for me in terms of data loss. It is important to note that the item for which the data is being lost is **NOT controlled by Unicorn**. Unicorn controlled items do not have this problem. The template however is controlled by Unicron.

**Sitecore log entries of moved template**
```
31680 06:18:53 INFO  AUDIT (sitecore\admin): Drag item: master:/sitecore/templates/Feature/UnicornTest/Test, language: da, version: 1, id: {646A66B2-7F74-45F0-B331-1115AB0472F1} to master:/sitecore/templates/Feature/UnicornTest/SubFolder, language: da, version: 1, id: {37E7A53C-6E74-46CC-805A-B8FC2656F7B6}
22980 06:18:53 DEBUG Min threads: 8, Active threads: 1.
31680 06:18:53 INFO  [Unicorn]: Serialization File System Data Store: Moved serialized item /sitecore/templates/Feature/UnicornTest/SubFolder/Test (646a66b2-7f74-45f0-b331-1115ab0472f1) to /sitecore/templates/Feature/UnicornTest/SubFolder
31680 06:18:53 INFO  [Unicorn]: Serialization File System Data Store: Ignored save of /sitecore/templates/Feature/UnicornTest/SubFolder/Test because it contained no consequential item changes.
ManagedPoolThread #2 06:18:53 INFO  Job started: Index_Update_IndexName=sitecore_master_index
```

**Unicorn Sync log on Instance B (the other Sitecore instance)**
```
Feature.UnicornTest is being synced.
[D] master:/sitecore/templates/Feature/UnicornTest/Test/Data/VersionedField (d7be8a18-d46e-4632-b0d4-1fa4528875c4) because it did not exist in the serialization provider. Can restore from recycle bin.
[D] master:/sitecore/templates/Feature/UnicornTest/Test/Data/SharedField (465777f4-d14e-4229-b70f-0a32d50b0863) because it did not exist in the serialization provider. Can restore from recycle bin.
[D] master:/sitecore/templates/Feature/UnicornTest/Test/Data/UnversionedField (ed4bc224-0266-4bf8-ae0b-1adffdba058b) because it did not exist in the serialization provider. Can restore from recycle bin.
[D] master:/sitecore/templates/Feature/UnicornTest/Test/Data (733f21cf-6450-4085-bda9-342c09e0690c) because it did not exist in the serialization provider. Can restore from recycle bin.
[D] master:/sitecore/templates/Feature/UnicornTest/Test (646a66b2-7f74-45f0-b331-1115ab0472f1) because it did not exist in the serialization provider. Can restore from recycle bin.
[A] master:/sitecore/templates/Feature/UnicornTest/SubFolder/Test (646a66b2-7f74-45f0-b331-1115ab0472f1)
[A] master:/sitecore/templates/Feature/UnicornTest/SubFolder/Test/Data (733f21cf-6450-4085-bda9-342c09e0690c)
[A] master:/sitecore/templates/Feature/UnicornTest/SubFolder/Test/Data/SharedField (465777f4-d14e-4229-b70f-0a32d50b0863)
[A] master:/sitecore/templates/Feature/UnicornTest/SubFolder/Test/Data/UnversionedField (ed4bc224-0266-4bf8-ae0b-1adffdba058b)
[A] master:/sitecore/templates/Feature/UnicornTest/SubFolder/Test/Data/VersionedField (d7be8a18-d46e-4632-b0d4-1fa4528875c4)

> Preparing to post-process synced items (links/indexes). May take some time depending on change count...
> Caches have been cleared and template engine reset. Resolving items...
> Post process items resolved.

[L] Updating link database for changed items.
> Updated 5 items in the link database in 13.00 sec

[I] Updating search indexes for changed items.
> Queued updates for 5 items in the search indexes. Will run async.
Feature.UnicornTest sync complete: 22 items evaluated, 10 items modified (5 added, 0 updated, 5 recycled) in 25608ms (~1,164.03ms/item).

Operation completed in 25610ms. Want to return to the control panel?
```

**Comment by zaheer-tariq** [comment] 2019-02-19 06:36
@cassidydotdk  Before disabling Dilithium, I could produce the issue in both scenarios i.e. when 
I move the template to a sub-folder and back. But after disabling Dilithium I ran few tests again and found that it happens when I move to sub-folder e.g.

/sitecore/templates/Feature/UnicornTest/Test 
to 
/sitecore/templates/Feature/UnicornTest/SubFolder

But NOT when I move 
/sitecore/templates/Feature/UnicornTest/SubFolder/Test 
to 
/sitecore/templates/Feature/UnicornTest

**Test** is the template name in above paths

In short the issue appears when the template is first deleted and then added.

**Sync log when the issue do NOT appear**
-------------------------------------------------------------------------------------------------------------------
```
Feature.UnicornTest is being synced.
[U] master:/sitecore/templates/Feature/UnicornTest/Test (646a66b2-7f74-45f0-b331-1115ab0472f1)
> Name: Serialized 'Test', Source 'Test'
* [M] from {37E7A53C-6E74-46CC-805A-B8FC2656F7B6} to {0301464E-5719-4F9F-903A-C3EBAB496687}

> Preparing to post-process synced items (links/indexes). May take some time depending on change count...
> Caches have been cleared and template engine reset. Resolving items...
> Post process items resolved.

[L] Updating link database for changed items.
> Updated 1 items in the link database in 5.00 sec

[I] Updating search indexes for changed items.
> Queued updates for 1 items in the search indexes. Will run async.
Feature.UnicornTest sync complete: 8 items evaluated, 1 item modified (0 added, 1 updated, 0 recycled) in 14751ms (~1,843.90ms/item).

Operation completed in 14752ms. Want to return to the control panel?
```

**Sync log when the issue appears**
-------------------------------------------------------------------------------------------------------------------
```
Feature.UnicornTest is being synced.
[D] master:/sitecore/templates/Feature/UnicornTest/Test/Data/VersionedField (d7be8a18-d46e-4632-b0d4-1fa4528875c4) because it did not exist in the serialization provider. Can restore from recycle bin.
[D] master:/sitecore/templates/Feature/UnicornTest/Test/Data/SharedField (465777f4-d14e-4229-b70f-0a32d50b0863) because it did not exist in the serialization provider. Can restore from recycle bin.
[D] master:/sitecore/templates/Feature/UnicornTest/Test/Data/UnversionedField (ed4bc224-0266-4bf8-ae0b-1adffdba058b) because it did not exist in the serialization provider. Can restore from recycle bin.
[D] master:/sitecore/templates/Feature/UnicornTest/Test/Data (733f21cf-6450-4085-bda9-342c09e0690c) because it did not exist in the serialization provider. Can restore from recycle bin.
[D] master:/sitecore/templates/Feature/UnicornTest/Test (646a66b2-7f74-45f0-b331-1115ab0472f1) because it did not exist in the serialization provider. Can restore from recycle bin.
[A] master:/sitecore/templates/Feature/UnicornTest/SubFolder/Test (646a66b2-7f74-45f0-b331-1115ab0472f1)
[A] master:/sitecore/templates/Feature/UnicornTest/SubFolder/Test/Data (733f21cf-6450-4085-bda9-342c09e0690c)
[A] master:/sitecore/templates/Feature/UnicornTest/SubFolder/Test/Data/SharedField (465777f4-d14e-4229-b70f-0a32d50b0863)
[A] master:/sitecore/templates/Feature/UnicornTest/SubFolder/Test/Data/UnversionedField (ed4bc224-0266-4bf8-ae0b-1adffdba058b)
[A] master:/sitecore/templates/Feature/UnicornTest/SubFolder/Test/Data/VersionedField (d7be8a18-d46e-4632-b0d4-1fa4528875c4)

> Preparing to post-process synced items (links/indexes). May take some time depending on change count...
> Caches have been cleared and template engine reset. Resolving items...
> Post process items resolved.

[L] Updating link database for changed items.
> Updated 5 items in the link database in 13.00 sec

[I] Updating search indexes for changed items.
> Queued updates for 5 items in the search indexes. Will run async.
Feature.UnicornTest sync complete: 22 items evaluated, 10 items modified (5 added, 0 updated, 5 recycled) in 25608ms (~1,164.03ms/item).

Operation completed in 25610ms. Want to return to the control panel?
```

**Comment by cassidydotdk** [comment] 2019-02-19 06:40
I have a theory. Are your Rainbow settings for SerializationFolderPathMaxLength the same on all environments?

    <setting name="Rainbow.SFS.SerializationFolderPathMaxLength" value="110" />

And if it is; what is your absolute root path (e.g. C:\Projects\MyProject\..\Unicorn)?

**Comment by zaheer-tariq** [comment] 2019-02-19 07:41
@cassidydotdk The Rainbow setting is the same in all environments which is

`<setting name="Rainbow.SFS.SerializationFolderPathMaxLength" value="150" />`

The absolute root path is 
InstanceA => E:\Projects\ABC\Publish\default.abcsite.local\App_Data\Unicorn
and
InstanceB => E:\ABC3\Publish\default.abcsite.azure\App_Data\Unicorn

**Comment by cassidydotdk** [comment] 2019-02-19 08:04
That is interesting. We may be dealing with some sort of wraparound bug. Here's a bit of data. Bear with me.

`150` means the following, taken out of `Rainbow.config`.

`248 - 8 - 150 - 30 = 60` => Item paths longer than 60 characters will be shortened.

```
	Example: A value of "90" for this setting will mean that item paths longer than 150 characters will be shortened, since Sitecore 
	reserves 8 characters (and 248 - 8 - 90 = 150). 
	Default value: 110
```

Now looking at your template.

```
/sitecore/templates/Feature/UnicornTest/SubFolder/Test (55)
/sitecore/templates/Feature/UnicornTest/Test/Data/SharedField (62)
/sitecore/templates/Feature/UnicornTest/Test/Data/VersionedField (65)
/sitecore/templates/Feature/UnicornTest/Test/Data/UnversionedField (67)
```

In this example, the template item itself `/sitecore/templates/Feature/UnicornTest/SubFolder/Test (55)` will not be shortened since it remains just under the limit of 60 characters. HOWEVER. All of the below items will be - as they all will have to do a wraparound.

```
/sitecore/templates/Feature/UnicornTest/Test/Data/SharedField (62)
/sitecore/templates/Feature/UnicornTest/Test/Data/VersionedField (65)
/sitecore/templates/Feature/UnicornTest/Test/Data/UnversionedField (67)
```

**Can you confirm the folder structure on disk for me please?**  If the content was serialized with 150 as a setting, you should be seeing no sub folders on `/sitecore/templates/Feature/UnicornTest/SubFolder/Test (55)`, these should be wrapped around and appear at the root of your repository.

Also; your 150 setting seems excessive, since your root folders are much much shorter.

```
E:\Projects\ABC\Publish\default.abcsite.local\App_Data\Unicorn (63)
E:\ABC3\Publish\default.abcsite.azure\App_Data\Unicorn (55)
```

**Comment by zaheer-tariq** [comment] 2019-02-19 08:17
@cassidydotdk Do you think reducing the 150 setting to 120 will help fix this issue?

The folder structure generated by Unicorn on the disk is as follows

```
E:\Projects\ABC\Publish\default.abcsite.local\App_Data\Unicorn\Feature.UnicornTest\Feature.UnicornTest.Templates\UnicornTest.yml
E:\Projects\ABC\Publish\default.abcsite.local\App_Data\Unicorn\Feature.UnicornTest\Feature.UnicornTest.Templates\UnicornTest\Test.yml
E:\Projects\ABC\Publish\default.abcsite.local\App_Data\Unicorn\Feature.UnicornTest\Feature.UnicornTest.Templates\UnicornTest\SubFolder.yml
E:\Projects\ABC\Publish\default.abcsite.local\App_Data\Unicorn\Feature.UnicornTest\Feature.UnicornTest.Templates\UnicornTest\Test\Data.yml
E:\Projects\ABC\Publish\default.abcsite.local\App_Data\Unicorn\Feature.UnicornTest\Feature.UnicornTest.Templates\UnicornTest\Test\Data\SharedField.yml
E:\Projects\ABC\Publish\default.abcsite.local\App_Data\Unicorn\Feature.UnicornTest\Feature.UnicornTest.Templates\UnicornTest\Test\Data\UnversionedField.yml
E:\Projects\ABC\Publish\default.abcsite.local\App_Data\Unicorn\Feature.UnicornTest\Feature.UnicornTest.Templates\UnicornTest\Test\Data\VersionedField.yml
```

**Comment by cassidydotdk** [comment] 2019-02-19 08:23
I'm not 100% sure, but I do feel it's somehow related. See how your path lengths come out very long, also because of your naming.

I normally use a short name notation for configs and predicates, to allow for as much room as possible. If you don't mind - could you try the following scenario:

Rename the config from `Feature.UnicornTest` to `F.Test` and rename the predicate from `Feature.UnicornTest.Templates` to just `Templates`?  (prefixing the config name once again here seems redundant).  Just to see if this changes the behaviour.  If it does, then at least we are getting somewhere.

**Comment by zaheer-tariq** [comment] 2019-02-19 08:49
@cassidydotdk Tried both i.e. renaming and changing setting to 120 but still have the same issue. Whenever the template is deleted and added back again the content is gone in Shared and Unversioned Fields. It does not happen with Versioned Fields.

Paths now are
E:\Projects\ABC\Publish\default.abcsite.local\App_Data\Unicorn\F.Test\Templates
and
E:\ABC3\Publish\default.abcsite.azure\App_Data\Unicorn\F.Test\Templates

**Comment by zaheer-tariq** [comment] 2019-02-20 05:39
@cassidydotdk Any update? We have another production deployment end of this week and last time this issue caused us a lot of trouble as we had to restore all shared and unversioned fields after the deployment. Thanks a lot for your help.

**Comment by cassidydotdk** [comment] 2019-02-20 08:42
At this time, no. I've run out of immediate ideas that might be causing this for you, so I'm going to have to set up a test instance that resembles all the configuration you've shown me here and see if I can reproduce it. Based on the results of that, we'll see what comes next.

**Comment by cassidydotdk** [comment] 2019-02-20 10:09
Ok, just to confirm the setup. I now have the following.

A Sitecore Template configured like this:

![image](https://user-images.githubusercontent.com/8483909/53083358-06fc1780-34ff-11e9-8318-93303bcbaf00.png)

I have a content item based on this template:

![image](https://user-images.githubusercontent.com/8483909/53083403-298e3080-34ff-11e9-82ff-1cef805d68c4.png)

I have a Unicorn configuration resembling yours, with an equivalent root path (except for the drive letter, which I'm sure we can rule out here).

```
<configuration xmlns:patch="http://www.sitecore.net/xmlconfig/">
	<sitecore>
		<unicorn>
			<configurations>
				<configuration name="Feature.UnicornTest">
					<targetDataStore physicalRootPath="C:\Projects\ABC\Publish\default.abcsite.local\App_Data\Unicorn" />

					<predicate>
						<include name="Feature.UnicornTest.Templates" database="master" path="/sitecore/templates/Feature/UnicornTest" />
					</predicate>
				</configuration>
			</configurations>
		</unicorn>
	</sitecore>
</configuration>

```

And I have a folder structure that now looks like this:

![image](https://user-images.githubusercontent.com/8483909/53083620-91dd1200-34ff-11e9-96d8-66522d172375.png)

I also have Rainbow configured as this: `<setting name="Rainbow.SFS.SerializationFolderPathMaxLength" value="150" />`

As far as I can tell, this should closely resemble your case am I correct?  

So what you're saying is; that if I am to move that Test template into a sub folder named `SubFolder`, RESET my database back to this state, then sync my updated configuration - the content item would lose it's field values. Am I understanding you 100% here?

**Comment by cassidydotdk** [comment] 2019-02-20 10:44
Anyway, giving that a go. Recording steps and outcome here.

First backing up the solution DB..

![image](https://user-images.githubusercontent.com/8483909/53085284-cf8f6a00-3502-11e9-9957-53f4ec6cae22.png)

Then creating `SubFolder` and moving the `Test` template there.

![image](https://user-images.githubusercontent.com/8483909/53085355-f483dd00-3502-11e9-80b2-dcf7d332995e.png)

Unicorn file repository now looks like this

![image](https://user-images.githubusercontent.com/8483909/53085393-11201500-3503-11e9-8cc4-bd0a7c666373.png)

Unicorn logged this

```
18012 11:30:02 INFO  AUDIT (sitecore\admin): Drag item: master:/sitecore/templates/Feature/UnicornTest/Test, language: en, version: 1, id: {A1EA7C4F-3BE0-40B4-AD02-8C7136AABA1D} to master:/sitecore/templates/Feature/UnicornTest/SubFolder, language: en, version: 1, id: {7A0C85CD-0791-476B-84BD-DB526B1CB247}
18012 11:30:02 INFO  [Unicorn]: Serialization File System Data Store: Moved serialized item /sitecore/templates/Feature/UnicornTest/SubFolder/Test (a1ea7c4f-3be0-40b4-ad02-8c7136aaba1d) to /sitecore/templates/Feature/UnicornTest/SubFolder
18012 11:30:02 INFO  [Unicorn]: Serialization File System Data Store: Ignored save of /sitecore/templates/Feature/UnicornTest/SubFolder/Test because it contained no consequential item changes.
```

YAML for `Test`

```
---
ID: "a1ea7c4f-3be0-40b4-ad02-8c7136aaba1d"
Parent: "7a0c85cd-0791-476b-84bd-db526b1cb247"
Template: "ab86861a-6030-46c5-b394-e8f99e8b87db"
Path: /sitecore/templates/Feature/UnicornTest/SubFolder/Test
DB: master
SharedFields:
- ID: "12c33f3f-86c5-43a5-aeb4-5598cec45116"
  Hint: __Base template
  Type: tree list
  Value: "{1930BBEB-7805-471A-A3BE-4858AC7CF696}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190220T095938Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
```

And just to make sure Unicorn DID update the parent ID correctly (log file states saving was ignored because of inconsequential changes) - it matches `SubFolder` correctly.

![image](https://user-images.githubusercontent.com/8483909/53085630-986d8880-3503-11e9-861a-c1892481b5d3.png)
 
This is now your target state. Going to reset IIS, restore the DB, warm up Sitecore and then Sync Unicorn. See what happens.

![image](https://user-images.githubusercontent.com/8483909/53085836-0e71ef80-3504-11e9-8d6a-21c7fd29b21f.png)

![image](https://user-images.githubusercontent.com/8483909/53085857-1df13880-3504-11e9-8923-328481dfa0d8.png)

Warming up Sitecore, it now looks like this again

![image](https://user-images.githubusercontent.com/8483909/53085922-46793280-3504-11e9-9ac7-8908409f0a6c.png)

Telling Unicorn to `Sync`

![image](https://user-images.githubusercontent.com/8483909/53085979-6577c480-3504-11e9-99c8-2d0be8d489a8.png)

(at first glance this looks somewhat surprising, I would have expected a [M] operation)

Unicorn log

```
5080 11:40:36 INFO  [Unicorn]: Feature.UnicornTest is being synced.
5080 11:40:37 INFO  [Unicorn]: [A] master:/sitecore/templates/Feature/UnicornTest/SubFolder (7a0c85cd-0791-476b-84bd-db526b1cb247)
5080 11:40:37 WARN  [Unicorn]: [D] master:/sitecore/templates/Feature/UnicornTest/Test/Data/UnversionedField (76119fc5-9d81-4aa5-bdc5-871fa5be6348) because it did not exist in the serialization provider. Can restore from recycle bin.
5080 11:40:37 WARN  [Unicorn]: [D] master:/sitecore/templates/Feature/UnicornTest/Test/Data/SharedField (231da582-48e9-465f-a83f-a973239f19bf) because it did not exist in the serialization provider. Can restore from recycle bin.
5080 11:40:37 WARN  [Unicorn]: [D] master:/sitecore/templates/Feature/UnicornTest/Test/Data/VersionedField (9b89f69b-7549-47fd-9021-35f5bb0e053a) because it did not exist in the serialization provider. Can restore from recycle bin.
5080 11:40:37 WARN  [Unicorn]: [D] master:/sitecore/templates/Feature/UnicornTest/Test/Data (7553dc36-67cd-431c-87f5-261328341443) because it did not exist in the serialization provider. Can restore from recycle bin.
5080 11:40:37 WARN  [Unicorn]: [D] master:/sitecore/templates/Feature/UnicornTest/Test (a1ea7c4f-3be0-40b4-ad02-8c7136aaba1d) because it did not exist in the serialization provider. Can restore from recycle bin.
5080 11:40:37 INFO  [Unicorn]: [A] master:/sitecore/templates/Feature/UnicornTest/SubFolder/Test (a1ea7c4f-3be0-40b4-ad02-8c7136aaba1d)
5080 11:40:37 INFO  [Unicorn]: [A] master:/sitecore/templates/Feature/UnicornTest/SubFolder/Test/Data (7553dc36-67cd-431c-87f5-261328341443)
5080 11:40:37 INFO  [Unicorn]: [A] master:/sitecore/templates/Feature/UnicornTest/SubFolder/Test/Data/SharedField (231da582-48e9-465f-a83f-a973239f19bf)
5080 11:40:37 WARN  All caches have been cleared. This can decrease performance considerably. DEBUG entries have to be enabled in log4net to see the corresponding stack trace.
ManagedPoolThread #4 11:40:37 INFO  Job started: Sitecore.ListManagement.Operations.UpdateListOperationsAgent
ManagedPoolThread #4 11:40:37 INFO  Job ended: Sitecore.ListManagement.Operations.UpdateListOperationsAgent (units processed: )
5080 11:40:40 INFO  [Unicorn]: [A] master:/sitecore/templates/Feature/UnicornTest/SubFolder/Test/Data/UnversionedField (76119fc5-9d81-4aa5-bdc5-871fa5be6348)
5080 11:40:40 WARN  All caches have been cleared. This can decrease performance considerably.
5080 11:40:42 INFO  [Unicorn]: [A] master:/sitecore/templates/Feature/UnicornTest/SubFolder/Test/Data/VersionedField (9b89f69b-7549-47fd-9021-35f5bb0e053a)
5080 11:40:42 INFO  [Unicorn]: Feature.UnicornTest sync complete: 23 items evaluated, 11 items modified (6 added, 0 updated, 5 recycled) in 5482ms (~238.39ms/item).
5080 11:40:42 INFO  [Unicorn]: 
5080 11:40:42 WARN  All caches have been cleared. This can decrease performance considerably.
5080 11:40:42 INFO  Unicorn: initiated synchronous publishing of synced items.
```

Template has been moved as expected

![image](https://user-images.githubusercontent.com/8483909/53086123-c3a4a780-3504-11e9-8115-7fa1a93afea4.png)

So now - the real kicker. How is our content item doing?

![image](https://user-images.githubusercontent.com/8483909/53086168-db7c2b80-3504-11e9-807a-c949c769492c.png)

Which means I can confirm this issue. Now that I can reliably reproduce it, I will look into why this is happening.

**Comment by zaheer-tariq** [comment] 2019-02-20 10:50
@cassidydotdk Thank you for the details, yes the steps are correct and as you can see the issue is producible. Please let me know if you need any assistance from my side.

**Comment by zaheer-tariq** [comment] 2019-02-22 07:36
@cassidydotdk Any update, is there a quick fix we can try to avoid this issue? Thank you

**Comment by cassidydotdk** [comment] 2019-02-25 14:35
A fix for this problem has just been committed. I will be publishing Rainbow 2.0.6-pre4 to NuGet within an hour or so. Please update your Rainbow version and see if it works for you. It solves the problem entirely on my local setup; Sitecore 9.0.1.

https://github.com/SitecoreUnicorn/Rainbow/commit/caddd38874a51442e5782961ec64322b3af79895

**Comment by cassidydotdk** [comment] 2019-02-25 14:37
FWIW I _could_ have found a way to make Rainbow issue a [M] command instead of [D] and [A] - but that would still have had problems when templates moved between predicates and configurations. This fix should effectively close the book on that.

**Comment by cassidydotdk** [comment] 2019-02-25 14:56
NuGet has now accepted and published the release.

https://www.nuget.org/packages/Rainbow/2.0.6-pre4

Please test it out and revert @zaheer-tariq

**Comment by zaheer-tariq** [comment] 2019-02-28 11:22
@cassidydotdk  I have tested the fix locally in different scenarios and found that the issue is resolved. We will gradually test the fix on staging, per-production and production environments. I will get back to you with details if we see the issue in any other scenario/environment. For now this issue can be closed. I really appreciate your help and support. Thank you

**Closed** 2019-03-23 21:14 UTC
